import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import openapiTS, { astToString } from "openapi-typescript";

type OpenApiDoc = {
  paths?: Record<string, Record<string, unknown>>;
};

type Endpoint = {
  path: string;
  method: string;
};

function resolveApiBaseUrl(): string {
  return process.env.VITE_API_BASE_URL ?? "http://127.0.0.1:8010/api/v1";
}

function resolveOpenApiUrl(apiBaseUrl: string): string {
  const origin = apiBaseUrl.replace(/\/api\/v1\/?$/, "");
  return `${origin}/openapi.json`;
}

function toEndpoints(doc: OpenApiDoc): Endpoint[] {
  const results: Endpoint[] = [];
  for (const [routePath, methodMap] of Object.entries(doc.paths ?? {})) {
    for (const method of Object.keys(methodMap ?? {})) {
      results.push({ path: routePath, method: method.toUpperCase() });
    }
  }
  return results.sort((a, b) => (a.path === b.path ? a.method.localeCompare(b.method) : a.path.localeCompare(b.path)));
}

function renderEndpointsFile(endpoints: Endpoint[]): string {
  const rows = endpoints.map((endpoint) => `  { path: "${endpoint.path}", method: "${endpoint.method}" },`).join("\n");
  return `// Auto-generated by tools/gen-openapi.ts. Do not edit by hand.

export type EndpointMethod = "GET" | "POST" | "PUT" | "PATCH" | "DELETE" | "OPTIONS" | "HEAD" | "TRACE";

export type OpenApiEndpoint = {
  path: string;
  method: EndpointMethod;
};

export const OPENAPI_ENDPOINTS: OpenApiEndpoint[] = [
${rows}
];

const ENDPOINT_SET = new Set(OPENAPI_ENDPOINTS.map((endpoint) => \`\${endpoint.method} \${endpoint.path}\`));

export function hasRoute(path: string, method: string): boolean {
  return ENDPOINT_SET.has(\`\${method.toUpperCase()} \${path}\`);
}
`;
}

async function loadOpenApiDoc(args: string[], openApiUrl: string): Promise<OpenApiDoc> {
  const forceBackend = args.includes("--from-backend");
  const fileFlagIndex = args.indexOf("--from-file");
  if (fileFlagIndex >= 0 && args[fileFlagIndex + 1]) {
    const fromFile = path.resolve(process.cwd(), args[fileFlagIndex + 1]);
    const raw = await readFile(fromFile, "utf-8");
    return JSON.parse(raw) as OpenApiDoc;
  }
  if (!forceBackend) {
    const defaultFile = path.resolve(process.cwd(), "src/api/openapi.json");
    try {
      const raw = await readFile(defaultFile, "utf-8");
      return JSON.parse(raw) as OpenApiDoc;
    } catch {
      // Fall through to backend fetch when no snapshot exists locally.
    }
  }

  let response: Response;
  try {
    response = await fetch(openApiUrl);
  } catch (error) {
    throw new Error(
      `Unable to reach backend OpenAPI at ${openApiUrl}. Use --from-file ./src/api/openapi.json for deterministic generation, or start backend and retry.`,
      { cause: error },
    );
  }

  if (!response.ok) {
    throw new Error(
      `OpenAPI request failed (${response.status}) at ${openApiUrl}. Ensure backend is running and serving /openapi.json.`,
    );
  }
  return (await response.json()) as OpenApiDoc;
}

async function main() {
  const apiBaseUrl = resolveApiBaseUrl();
  const openApiUrl = resolveOpenApiUrl(apiBaseUrl);
  const args = process.argv.slice(2);

  const doc = await loadOpenApiDoc(args, openApiUrl);
  const endpoints = toEndpoints(doc);
  const generatedDir = path.resolve(process.cwd(), "src/gen");
  await mkdir(generatedDir, { recursive: true });

  const openapiTypesAst = await openapiTS(doc);
  const openapiTypesText = astToString(openapiTypesAst);
  const openapiTypesPath = path.join(generatedDir, "openapi-types.ts");
  const endpointsPath = path.join(generatedDir, "openapi-endpoints.ts");

  await writeFile(openapiTypesPath, `// Auto-generated by tools/gen-openapi.ts. Do not edit by hand.\n${openapiTypesText}`);
  await writeFile(endpointsPath, renderEndpointsFile(endpoints));

  console.log(`Generated:\n- ${openapiTypesPath}\n- ${endpointsPath}`);
}

main().catch((error) => {
  const message = error instanceof Error ? error.message : String(error);
  console.error(`gen:api failed: ${message}`);
  process.exit(1);
});
