import type { ModuleDefinition } from "./module-scaffold";

export const moduleDefinitions: ModuleDefinition[] = [
  {
    id: "sales",
    navLabel: "Sales",
    routeBase: "/sales",
    routePolicy: "SALES",
    tenantScoped: true,
    pages: [
      { path: "dashboard", title: "Dashboard", purpose: "Track pipeline activity.", data: "Pipeline KPIs and owner queues.", actions: "Open lead, assign owner, prioritize work." },
      { path: "leads", title: "Leads", purpose: "Manage inbound opportunities.", data: "Lead source, stage, and last contact.", actions: "Create lead, qualify, convert." },
      { path: "customers", title: "Customers", purpose: "View customer profiles.", data: "Identity, vehicles, communication history.", actions: "Open profile, update contact, start deal." },
      { path: "deals", title: "Deals", purpose: "Track active and pending deals.", data: "Deal status, desk numbers, approvals.", actions: "Create deal, move stage, request approval." },
      { path: "desk", title: "Desk", purpose: "Work deal structure drafts.", data: "Worksheet details and assumptions.", actions: "Open worksheet, save version, share." },
      { path: "settings", title: "Settings", purpose: "Configure Sales module defaults.", data: "Role summaries and workflow settings.", actions: "Review role matrix, adjust defaults." },
    ],
  },
  {
    id: "fi",
    navLabel: "F&I",
    routeBase: "/fi",
    routePolicy: "FI",
    tenantScoped: true,
    pages: [
      { path: "dashboard", title: "Dashboard", purpose: "Monitor contract completion and blockers.", data: "Submission counts and pending stips.", actions: "Open contract, resolve blocker." },
      { path: "contracts", title: "Contracts", purpose: "Review contract pipeline.", data: "Status, lender, funding state.", actions: "Create contract, update details." },
      { path: "stips", title: "Stips", purpose: "Track missing required docs.", data: "Checklist by contract and owner.", actions: "Mark received, escalate." },
      { path: "funding", title: "Funding", purpose: "Watch held funding queue.", data: "Aging funding tasks and notes.", actions: "Assign follow-up, mark funded." },
      { path: "products", title: "Products", purpose: "Manage F&I product catalog.", data: "Coverage options and pricing stubs.", actions: "Add product, disable product." },
      { path: "settings", title: "Settings", purpose: "Configure F&I defaults.", data: "Role and workflow preferences.", actions: "Review permissions, update defaults." },
    ],
  },
  {
    id: "service",
    navLabel: "Service",
    routeBase: "/service",
    routePolicy: "SERVICE",
    tenantScoped: true,
    pages: [
      { path: "dashboard", title: "Dashboard", purpose: "See today's service workload.", data: "Appointment and bay summary.", actions: "Open RO, view advisor queue." },
      { path: "appointments", title: "Appointments", purpose: "Manage service schedule.", data: "Calendar/list of appointments.", actions: "Create appointment, reschedule." },
      { path: "repair-orders", title: "Repair Orders", purpose: "Track open repair orders.", data: "RO status, customer, vehicle.", actions: "Open RO, assign tech, update status." },
      { path: "estimates", title: "Estimates", purpose: "Prepare customer estimates.", data: "Estimate lines and totals placeholder.", actions: "Create estimate, request approval." },
      { path: "inspections", title: "Inspections", purpose: "Capture MPI outcomes.", data: "Inspection checklist and notes.", actions: "Record result, attach media." },
      { path: "settings", title: "Settings", purpose: "Configure Service defaults.", data: "Team roles and workflow settings.", actions: "Review policy, update defaults." },
    ],
  },
  {
    id: "parts",
    navLabel: "Parts",
    routeBase: "/parts",
    routePolicy: "PARTS",
    tenantScoped: true,
    pages: [
      { path: "dashboard", title: "Dashboard", purpose: "Monitor parts operations.", data: "Open quotes, stock alerts.", actions: "Open catalog, create order." },
      { path: "catalog", title: "Catalog", purpose: "Search part catalog.", data: "Part numbers and fitment placeholders.", actions: "Search, pin frequent parts." },
      { path: "quotes", title: "Quotes", purpose: "Track active parts quotes.", data: "Quote status and expiry.", actions: "Create quote, send to customer." },
      { path: "orders", title: "Orders", purpose: "Manage purchase orders.", data: "PO lifecycle and receipt stubs.", actions: "Create PO, mark received." },
      { path: "inventory", title: "Inventory", purpose: "See parts stock by location.", data: "Bin/location and quantity placeholders.", actions: "Adjust stock, relocate bin." },
      { path: "settings", title: "Settings", purpose: "Configure Parts module defaults.", data: "Role and workflow settings.", actions: "Update reorder defaults." },
    ],
  },
  {
    id: "acct",
    navLabel: "Accounting",
    routeBase: "/acct",
    routePolicy: "ACCOUNTING",
    tenantScoped: true,
    featureFlag: "accountingBeta",
    pages: [
      { path: "dashboard", title: "Dashboard", purpose: "Track close and posting readiness.", data: "Posting queue and period status.", actions: "Open journal, review batch." },
      { path: "journals", title: "Journals", purpose: "View journal entries.", data: "Journal lists and posting status.", actions: "Create journal, edit draft." },
      { path: "batches", title: "Batches", purpose: "Manage posting batches.", data: "Batch status and totals placeholders.", actions: "Create batch, lock batch." },
      { path: "periods", title: "Periods", purpose: "Control accounting periods.", data: "Open/close state by period.", actions: "Open period, close period." },
      { path: "reports", title: "Reports", purpose: "Access accounting report stubs.", data: "Trial balance and statements placeholder.", actions: "Run report, export." },
      { path: "settings", title: "Settings", purpose: "Configure accounting defaults.", data: "Posting and access preferences.", actions: "Review controls, update defaults." },
    ],
  },
  {
    id: "comms",
    navLabel: "Comms",
    routeBase: "/comms",
    routePolicy: "COMMS",
    tenantScoped: true,
    featureFlag: "commsEnabled",
    pages: [
      { path: "inbox", title: "Inbox", purpose: "Track customer conversations.", data: "Conversation list and activity summary.", actions: "Open thread, assign owner." },
      { path: "templates", title: "Templates", purpose: "Manage reusable message templates.", data: "Template names and tags.", actions: "Create template, archive template." },
      { path: "approvals", title: "Approvals", purpose: "Handle customer approval flows.", data: "Pending approval requests placeholder.", actions: "Request approval, remind customer." },
      { path: "audit", title: "Audit", purpose: "Review communications audit trail.", data: "Message event timeline placeholders.", actions: "Filter audit entries, export log." },
      { path: "settings", title: "Settings", purpose: "Configure messaging defaults.", data: "Channels and policy stubs.", actions: "Update defaults, test channel." },
    ],
  },
  {
    id: "inv",
    navLabel: "Inventory",
    routeBase: "/inv",
    routePolicy: "INVENTORY",
    tenantScoped: true,
    pages: [
      { path: "dashboard", title: "Dashboard", purpose: "Review inventory health.", data: "Turn, aging, and stock mix placeholders.", actions: "Open vehicle, adjust strategy." },
      { path: "vehicles", title: "Vehicles", purpose: "Manage inventory units.", data: "Vehicle list and detail placeholders.", actions: "Create unit, update details." },
      { path: "pricing", title: "Pricing", purpose: "Manage pricing rule stubs.", data: "Rule set placeholders.", actions: "Create rule, simulate impact." },
      { path: "acquisitions", title: "Acquisitions", purpose: "Track trades and buys.", data: "Acquisition queue placeholders.", actions: "Create acquisition, assign buyer." },
      { path: "settings", title: "Settings", purpose: "Configure inventory defaults.", data: "Rule and approval settings placeholders.", actions: "Update policy, review permissions." },
    ],
  },
  {
    id: "reports",
    navLabel: "Reports",
    routeBase: "/reports",
    routePolicy: "REPORTS",
    tenantScoped: true,
    pages: [
      { path: "library", title: "Library", purpose: "Browse report catalog.", data: "Report tiles and metadata placeholders.", actions: "Open report, save favorite." },
      { path: "scheduled", title: "Scheduled", purpose: "Manage scheduled report runs.", data: "Schedule stubs and recipients.", actions: "Create schedule, pause schedule." },
      { path: "export", title: "Export", purpose: "Configure export jobs.", data: "Export queue and destination stubs.", actions: "Start export, download file." },
    ],
  },
];
